json.id pin.id
json.description pin.description
json.creator_id pin.creator_id
json.creator pin.user.name
json.keywords pin.keywords
json.link_url pin.link_url
json.board_id pin.board_id
json.board_name pin.board.name
json.title pin.title
json.image_url asset_path(pin.image.url(:original))
